[package]
name = "at-collection"
version = "0.1.0"
authors = ["Phillip Lord <phillip.lord@russet.org.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
