[package]
name = "at-collection"
version = "0.1.0"
authors = ["Phillip Lord <phillip.lord@russet.org.uk>"]
description = "Collections with minimum or maximum number of entities"
license = "LGPL-3.0"
edition = "2018"

[dependencies]
